"""add_port_to_routers

Revision ID: 78fdbc06c3bf
Revises: 6420f4129bb8
Create Date: 2026-04-27 18:06:44.477860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fdbc06c3bf'
down_revision: Union[str, None] = '6420f4129bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('port', sa.Integer(), nullable=False, server_default='8728'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routers', 'port')
    # ### end Alembic commands ###
